# Generated by Django 2.1.4 on 2018-12-29 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('zjj', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor1_total_value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('factor2_total_value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('factor3_total_value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('factor4_total_value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('factor5_total_value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('factor6_total_value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('factor7_total_value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('factor8_total_value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('factor9_total_value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('factor10_total_value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('quetoans', models.CharField(max_length=2048)),
                ('starttime', models.DateTimeField()),
                ('endtime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Testchart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=512)),
                ('status', models.IntegerField()),
                ('isdelete', models.BooleanField(default=False)),
                ('jobneed_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zjj.Jobneed')),
                ('teser_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zjj.Tester')),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='testchart_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cjb.Testchart'),
        ),
    ]
