# Generated by Django 2.1.4 on 2018-12-29 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=2048)),
                ('factor1_value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('factor2_value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('factor3_value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('factor4_value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('factor5_value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('factor6_value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('factor7_value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('factor8_value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('factor9_value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('factor10_value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('isdelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Qustion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('qustion_type', models.CharField(max_length=100)),
                ('isdelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fxj.Qustion'),
        ),
    ]
