# Generated by Django 2.1.4 on 2018-12-29 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qsj', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelDesign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor_ex_value', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='moding',
            name='factor1_ex_value',
        ),
        migrations.RemoveField(
            model_name='moding',
            name='factor1_id',
        ),
        migrations.RemoveField(
            model_name='moding',
            name='factor2_ex_value',
        ),
        migrations.RemoveField(
            model_name='moding',
            name='factor3_ex_value',
        ),
        migrations.RemoveField(
            model_name='moding',
            name='factor4_ex_value',
        ),
        migrations.RemoveField(
            model_name='moding',
            name='factor5_ex_value',
        ),
        migrations.RemoveField(
            model_name='moding',
            name='factor6_ex_value',
        ),
        migrations.RemoveField(
            model_name='moding',
            name='factor7_ex_value',
        ),
        migrations.RemoveField(
            model_name='moding',
            name='factor8_ex_value',
        ),
        migrations.AlterField(
            model_name='factor',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='moding',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='modeldesign',
            name='factor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qsj.Factor'),
        ),
        migrations.AddField(
            model_name='modeldesign',
            name='moding_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qsj.Moding'),
        ),
    ]
