# Generated by Django 2.1.4 on 2018-12-29 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qsj', '0002_auto_20181229_0708'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='isdelete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='factor',
            name='isdelete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='modeldesign',
            name='isdelete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='moding',
            name='isdelete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useradmin',
            name='isdelete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userexpert',
            name='isdelete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userhr',
            name='isdelete',
            field=models.BooleanField(default=False),
        ),
    ]
