# Generated by Django 2.1.4 on 2019-01-03 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qsj', '0003_auto_20181229_0711'),
    ]

    operations = [
        migrations.AddField(
            model_name='userhr',
            name='hrname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
