# Generated by Django 2.1.4 on 2019-01-03 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zjj', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobneed',
            name='create_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='jobneed',
            name='create_user_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='jobneed',
            name='jobneed_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='jobneed',
            name='jobneed_status',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='jobneed',
            name='job_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='zjj.Job'),
        ),
        migrations.AlterField(
            model_name='jobneed',
            name='moding_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='qsj.Moding'),
        ),
    ]
