# Generated by Django 2.1.4 on 2019-01-03 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zjj', '0002_auto_20190103_0325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobneed',
            name='job_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zjj.Job'),
        ),
        migrations.AlterField(
            model_name='jobneed',
            name='moding_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qsj.Moding'),
        ),
    ]
