# Generated by Django 2.1.4 on 2019-01-03 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zjj', '0003_auto_20190103_0335'),
    ]

    operations = [
        migrations.AddField(
            model_name='tester',
            name='create_hr',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='tester',
            name='jobneed_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zjj.Jobneed'),
        ),
        migrations.AlterField(
            model_name='tester',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
