# Generated by Django 2.1.4 on 2019-01-03 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zjj', '0005_auto_20190103_0658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobneed',
            old_name='create_user_name',
            new_name='create_hr_id',
        ),
        migrations.RenameField(
            model_name='tester',
            old_name='create_hr',
            new_name='create_hr_id',
        ),
    ]
