# Generated by Django 2.1.4 on 2019-01-03 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zjj', '0007_remove_job_company_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tester',
            name='jobneed_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jn_id', to='zjj.Jobneed'),
        ),
    ]
