# Generated by Django 2.1.4 on 2019-01-04 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zjj', '0008_auto_20190103_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tester',
            name='jobneed_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zjj.Jobneed'),
        ),
    ]
